version: '3'
services:
  mongo:
    image: 'mongo:6'
    environment:
      - MONGO_INITDB_DATABASE=webinar
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=ognom
      - TZ=Europe/Paris
    ports:
      - '3702:27017'
  mongo-admin:
    image: 'mongo-express'
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=ognom
    ports:
      - '3703:8081'
    depends_on:
      - mongo
